Sate that it's 0

diff --git a/check/format-incremental b/check/format-incremental
--- a/check/format-incremental
+++ b/check/format-incremental
@@ -130,9 +130,9 @@ fi
 # black "${args[@]}" ${format_files}
 # exit $?
 LOGS="$(black "${args[@]}" ${format_files} 2>&1)"
-BLACKSTATUS=$
+BLACKSTATUS=$?
 echo "${LOGS}"
-if [[ "$STATUS" == "123" && "$LOGS" =~ ^.*"INTERNAL ERROR: Black produced different code on the second pass of the formatter.".*$ ]]; then
+if [[ "$BLACKSTATUS" == "123" && "$LOGS" =~ ^.*"INTERNAL ERROR: Black produced different code on the second pass of the formatter.".*$ ]]; then
   echo -e "\033[31mWarning, it seems we ran into https://github.com/psf/black/issues/1629. Typically, this can be fixed by adding a trailing comma. If you get stuck, please file a cirq issue on github.\033[0m"
 fi
 
