Remove unnecessary quotes
Shell does not split or glob sub-shell output in `var=$(command)` assignments.

diff --git a/check/shellcheck b/check/shellcheck
--- a/check/shellcheck
+++ b/check/shellcheck
@@ -12,8 +12,8 @@
 ################################################################################
 
 # Change working directory to the repository root.
-thisdir="$(dirname "${BASH_SOURCE[0]}")" || exit $?
-topdir="$(git -C "${thisdir}" rev-parse --show-toplevel)" || exit $?
+thisdir=$(dirname "${BASH_SOURCE[0]}") || exit $?
+topdir=$(git -C "${thisdir}" rev-parse --show-toplevel) || exit $?
 cd "${topdir}" || exit $?
 
 # Process command line arguments
@@ -51,9 +51,9 @@ required_shell_scripts=(
     dev_tools/pypath
 )
 
-scripts_not_found="$(comm -13 \
+scripts_not_found=$(comm -13 \
     <(printf "%s\n" "${our_shell_scripts[@]}") \
-    <(printf "%s\n" "${required_shell_scripts[@]}") )"
+    <(printf "%s\n" "${required_shell_scripts[@]}") )
 
 if [[ -n "${scripts_not_found}" ]]; then
     echo "Identification of shell scripts failed - files not found:" >&2
