DROPME - temporarily upgrade to numpy-1.24.2
Temporarily upgrade to numpy-1.24.2 to enable CI testing of #5991.

Restrict CI-tests to Python 3.8 only which permits installation of
numpy-1.24.2 and numba.  Note numba is not yet compatible with
numpy-1.24 and its import raises SystemError exception
SystemError: initialization of _internal failed without raising an exception

Here we also add intentionally failing CI check to ensure this commit
is not accidentally merged to master.

Please revert this commit before merging the pull-request.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -149,7 +149,7 @@ jobs:
     name: Pytest Ubuntu
     strategy:
       matrix:
-        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
+        python-version: [ '3.8' ]
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2
@@ -185,6 +185,17 @@ jobs:
       - name: Test dependencies with pip-compile
         run: |
           pip-compile --resolver=backtracking dev_tools/requirements/deps/cirq-all.txt -o-
+  numpy-1_24-guard:
+    name: Deliberate failure for numpy-1.24
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v2
+      - name: Exit with error status
+        run: |
+          echo "This check fails to prevent merging of a temporary upgrade to numpy-1.24"
+          echo
+          echo "Please revert the commit which introduced this test."
+          exit 1
   build_docs:
     name: Build docs
     runs-on: ubuntu-20.04
@@ -244,7 +255,7 @@ jobs:
     name: Pytest Windows
     strategy:
       matrix:
-        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
+        python-version: [ '3.8' ]
     runs-on: windows-2019
     steps:
       - uses: actions/checkout@v2
@@ -269,7 +280,7 @@ jobs:
     name: Pytest MacOS
     strategy:
       matrix:
-        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
+        python-version: [ '3.8' ]
     runs-on: macos-12
     steps:
       - uses: actions/checkout@v2
