Invoke the labeler program directly
There is no way to get the error messages from the labeler action. We
need to get the output if we want to note that something failed
without failing the whole workflow. Thankfully, the action can be
invoked more directly using `podman`, and it's not hard to revise the
workflow to capture the output and write it as an annotation on the
summary page.

diff --git a/.github/workflows/pr-labeler.yaml b/.github/workflows/pr-labeler.yaml
--- a/.github/workflows/pr-labeler.yaml
+++ b/.github/workflows/pr-labeler.yaml
@@ -14,6 +14,10 @@
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 # Label PRs with labels such as size.
+#
+# This workflow is designed not to fail if labeling actions encounter errors;
+# instead, the actions write annotations on the workflow run summary page. If
+# labels don't seem to be getting applied as expected, check there for errors.
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 name: Pull request labeler
@@ -34,7 +38,7 @@ permissions: read-all
 
 jobs:
   label-pr-size:
-    name: Update size labels on a PR
+    name: Update PR size labels
     runs-on: ubuntu-24.04
     permissions:
       id-token: write
@@ -45,14 +49,31 @@ jobs:
       # We need a copy of the repo so the action can read the config file.
       - name: Check out a copy of the git repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          fetch-depth: 0
 
       - name: Label the PR with a size label
-        uses: cbrgm/pr-size-labeler-action@85f918ef4ef0a7dbc08166774f9158697584bc8c # v1
+        id: label
         continue-on-error: true
-        with:
-          github_token: ${{secrets.GITHUB_TOKEN}}
-          github_pr_number: ${{github.event.number}}
-          github_repository: ${{github.repository}}
-          config_file_path: '.github/pr-size-labels.yaml'
+        run: |
+          set -x +e
+          podman --out action.out run -v .github:/tmp/.github --rm -it \
+            ghcr.io/cbrgm/pr-size-labeler-action:v1 \
+            --githubtoken ${{secrets.GITHUB_TOKEN}} \
+            --eventname pull_request \
+            --reponame ${{github.repository}} \
+            --prnumber ${{github.event.number}} \
+            --configfilepath /tmp/.github/pr-size-labels.yaml
+          status=$?
+          echo '::group::Labeler action output'
+          cat action.out
+          echo '::endgroup::'
+          exit $status
+
+      - name: Detect and report errors in labeler action
+        if: steps.label.outcome == 'failure' || steps.label.outcome == 'error'
+        run: |
+          {
+          echo "<h4>‼️ Failed to label PR ${{github.event.number}}</h4>"
+          echo "<pre>"
+          cat action.out
+          echo "</pre>"
+          } >> "$GITHUB_STEP_SUMMARY"
